# Generated by Django 5.0.3 on 2024-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_cart',
            field=models.IntegerField(default=0),
        ),
    ]
